package main

import (
	"encoding/json"
	"testing"
)

func TestScrapePayloadContract(t *testing.T) {
	// Simulate the JSON payload generated by the Python scraper's Pydantic model
	// (scraper/models.py -> ScrapePayload)
	pythonPayloadJSON := `{
		"trace_id": "12345-abcde",
		"source_url": "https://www.instagram.com/p/C1234567890/",
		"platform": "instagram",
		"raw_caption": "Delicious recipe!",
		"timestamp": "2023-10-27T10:00:00Z",
		"scraped_at": "2023-10-27T10:05:00Z"
	}`

	var payload ScrapePayload
	err := json.Unmarshal([]byte(pythonPayloadJSON), &payload)
	if err != nil {
		t.Fatalf("Failed to unmarshal python payload: %v", err)
	}

	if payload.TraceID != "12345-abcde" {
		t.Errorf("Expected TraceID '12345-abcde', got '%s'", payload.TraceID)
	}
	if payload.SourceURL != "https://www.instagram.com/p/C1234567890/" {
		t.Errorf("Expected SourceURL 'https://www.instagram.com/p/C1234567890/', got '%s'", payload.SourceURL)
	}
	if payload.Platform != "instagram" {
		t.Errorf("Expected Platform 'instagram', got '%s'", payload.Platform)
	}
	if payload.RawCaption != "Delicious recipe!" {
		t.Errorf("Expected RawCaption 'Delicious recipe!', got '%s'", payload.RawCaption)
	}
	// Note: timestamp and scraped_at are correctly ignored by Go's JSON unmarshaler
}
